export type ThemeType = 'light' | 'dark';

export const Colors = {
    light: {
        background: '#f8f9fe',
        backgroundGradient: ['#fef6fa', '#f8f9fe', '#f8f9fe'] as const,
        textPrimary: '#1e293b',
        textSecondary: '#64748b',
        textTitle: '#1e293b',
        primary: '#9d4edd',
        primaryLight: '#c77dff',
        cardBackground: '#ffffff',
        cardBorder: '#f1f5f9',
        dailyNumberCircleOuter: 'rgba(157, 78, 221, 0.12)',
        dailyNumberCircleInner: '#fbf7ff',
        heroNumberColor: '#9d4edd',
        heroLabelColor: 'rgba(157, 78, 221, 0.6)',
        heroGlowColor: 'rgba(157, 78, 221, 0.35)',
        guidanceTitle: '#e0aa3e',
        guidanceText: '#334155',
        chartBackground: '#ffffff',
        biorhythmTrack: '#f1f5f9',
        tabBarBackground: 'rgba(255, 255, 255, 0.95)',
        tabBarActive: '#9d4edd',
        tabBarInactive: '#94a3b8',
        dateHeader: '#64748b',
        notificationBadge: '#ffffff',
        categoryIconBackground: '#ffffff',
        categoryIconBorder: 'transparent',
        categoryCardShadow: 'rgba(157, 78, 221, 0.06)',
        chartLegendText: '#64748b',
        biorhythmChartLine1: '#ffb3c1',
        biorhythmChartLine2: '#a2d2ff',
        biorhythmChartLine3: '#b7e4c7',
        biorhythmValueColor: '#334155',
        biorhythmLabelColor: '#94a3b8',
        switchTrackOff: '#d4d4d4',
        switchThumb: '#f4f3f4',
        sectionTitle: 'Explore',
        headerCentered: false,
        settingsSectionTitle: '#94a3b8',
        settingsAvatarCircle: '#e9d5ff',
        settingsAvatarIcon: '#9d4edd',
        settingsIconBg: '#f1f5f9',
        settingsChevron: '#94a3b8',
        toggleActive: '#9d4edd',
        toggleInactive: '#e2e8f0',
        themeSwitchBg: '#f1f5f9',
        themeSwitchActiveBg: '#ffffff',
        themeSwitchTextActive: '#9d4edd',
        themeSwitchTextInactive: '#64748b',
        logoutText: '#ef4444',
        logoutBg: '#fef2f2',
        doneButton: '#9d4edd',
        categoryColors: {
            lifePath: { color: '#ffb3c1', bgFill: '#fef6fa' },
            soulUrge: { color: '#b7e4c7', bgFill: '#f6fdf9' },
            expression: { color: '#a2d2ff', bgFill: '#f4faff' },
            destiny: { color: '#e0aa3e', bgFill: '#fffbf0' },
            psychomatrix: { color: '#e0aa3e', bgFill: '#fffbf0' },
        },
    },
    dark: {
        background: '#0c4a6e',
        backgroundGradient: ['#0369a1', '#0c4a6e', '#082f49'] as const,
        textPrimary: '#f0f9ff',
        textSecondary: '#bae6fd',
        textTitle: '#ffffff',
        primary: '#38bdf8',
        primaryLight: '#7dd3fc',
        cardBackground: 'rgba(255, 255, 255, 0.1)',
        cardBorder: 'rgba(186, 230, 253, 0.4)',
        dailyNumberCircleOuter: 'rgba(186, 230, 253, 0.25)',
        dailyNumberCircleInner: 'rgba(255, 255, 255, 0.12)',
        heroNumberColor: '#ffffff',
        heroLabelColor: '#ffffff',
        heroGlowColor: 'rgba(56, 189, 248, 0.4)',
        guidanceTitle: '#ffffff',
        guidanceText: '#f0f9ff',
        chartBackground: 'rgba(255, 255, 255, 0.1)',
        biorhythmTrack: 'rgba(255, 255, 255, 0.15)',
        tabBarBackground: 'rgba(12, 74, 110, 0.9)',
        tabBarActive: '#ffffff',
        tabBarInactive: '#bae6fd',
        dateHeader: '#bae6fd',
        notificationBadge: 'rgba(255, 255, 255, 0.2)',
        categoryIconBackground: 'rgba(255, 255, 255, 0.1)',
        categoryIconBorder: 'rgba(255, 255, 255, 0.4)',
        categoryCardShadow: 'rgba(31, 38, 135, 0.25)',
        settingsSectionTitle: '#bae6fd',
        settingsAvatarCircle: 'rgba(255, 255, 255, 0.1)',
        settingsAvatarIcon: '#38bdf8',
        settingsIconBg: 'rgba(255, 255, 255, 0.05)',
        settingsChevron: '#bae6fd',
        toggleActive: '#38bdf8',
        toggleInactive: 'rgba(255, 255, 255, 0.1)',
        themeSwitchBg: 'rgba(0, 0, 0, 0.2)',
        themeSwitchActiveBg: '#38bdf8',
        themeSwitchTextActive: '#0c4a6e',
        themeSwitchTextInactive: '#bae6fd',
        logoutText: '#ff8a8a',
        logoutBg: 'rgba(255, 138, 138, 0.1)',
        doneButton: '#38bdf8',
        chartLegendText: '#ffffff',
        biorhythmChartLine1: '#ffffff',
        biorhythmChartLine2: '#bae6fd',
        biorhythmChartLine3: '#7dd3fc',
        biorhythmValueColor: '#ffffff',
        biorhythmLabelColor: '#ffffff',
        switchTrackOff: '#2A4A5E',
        switchThumb: '#ffffff',
        sectionTitle: 'Categories',
        headerCentered: true,
        categoryColors: {
            lifePath: { color: '#ffffff', bgFill: 'rgba(255, 255, 255, 0.1)' },
            soulUrge: { color: '#ffffff', bgFill: 'rgba(255, 255, 255, 0.1)' },
            expression: { color: '#ffffff', bgFill: 'rgba(255, 255, 255, 0.1)' },
            destiny: { color: '#bae6fd', bgFill: 'rgba(255, 255, 255, 0.1)' },
            psychomatrix: { color: '#ffffff', bgFill: 'rgba(255, 255, 255, 0.1)' },
        },
    },
};
